//! Schema proposal types for LLM-based schema suggestion.
//!
//! These types represent the schema lifecycle: a proposal generated by
//! sampling documents and analyzing them with an LLM, which can then be
//! reviewed, approved, or rejected before ingestion begins.

use serde::{Deserialize, Serialize};

/// Status of a schema proposal in its lifecycle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SchemaStatus {
    /// No schema has been proposed yet.
    None,
    /// Schema has been proposed but not yet reviewed.
    Proposed,
    /// Schema has been approved for use in ingestion.
    Approved,
    /// Schema was rejected and needs revision.
    Rejected,
}

impl Default for SchemaStatus {
    fn default() -> Self {
        SchemaStatus::None
    }
}

/// Input parameters for the schema suggestion workflow.
///
/// Replaces the old `(sample_percentage, domain_hint)` parameter pair with
/// a richer struct that supports stratified sampling, user-specified types,
/// and domain configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SuggestSchemaInput {
    /// What domain is this data from? (e.g. "legal", "healthcare", "finance")
    pub domain_description: Option<String>,
    /// User-specified entity types to guarantee in output.
    pub expected_entity_types: Option<Vec<String>>,
    /// User-specified relationship types to guarantee in output.
    pub expected_relationship_types: Option<Vec<String>>,
    /// Backward-compatible alias for domain_description.
    pub domain_hint: Option<String>,
    /// Total sampling budget (default: 24 documents).
    pub sample_budget: Option<usize>,
}

/// Metadata about the stratified sampling process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SamplingMetadata {
    /// Total documents in the dataset.
    pub total_documents: usize,
    /// Number of documents actually sampled.
    pub sampled_count: usize,
    /// Breakdown by size bucket.
    pub buckets: BucketBreakdown,
    /// Number of distinct topic clusters found via TF-IDF.
    pub topic_clusters_found: usize,
    /// Auto-detected persona (filled by Plan 14-02 later).
    pub auto_persona: Option<String>,
}

/// Size bucket breakdown for sampling metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BucketBreakdown {
    /// Short documents (< 1000 chars).
    pub short: BucketInfo,
    /// Medium documents (1000-5000 chars).
    pub medium: BucketInfo,
    /// Long documents (> 5000 chars).
    pub long: BucketInfo,
}

/// Info about a single size bucket.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BucketInfo {
    /// Number of documents available in this bucket.
    pub available: usize,
    /// Number of documents sampled from this bucket.
    pub sampled: usize,
}

/// A complete schema proposal generated by analyzing sampled documents.
///
/// Contains proposed entity and relation types along with metadata about
/// the sampling and review process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaProposal {
    /// Current status of the schema.
    pub status: SchemaStatus,
    /// Proposed entity types with descriptions and frequency counts.
    pub entity_types: Vec<EntityTypeProposal>,
    /// Proposed relation types with descriptions and constraints.
    pub relation_types: Vec<RelationTypeProposal>,
    /// Number of documents sampled.
    pub sample_size: usize,
    /// Total documents in dataset.
    pub total_documents: usize,
    /// Optional domain hint provided by partner.
    pub domain_hint: Option<String>,
    /// When the proposal was generated (epoch milliseconds).
    pub proposed_at: i64,
    /// When the proposal was approved/rejected (epoch milliseconds), if applicable.
    pub reviewed_at: Option<i64>,
    /// Metadata about the stratified sampling process.
    #[serde(default)]
    pub sampling_metadata: Option<SamplingMetadata>,
}

/// A proposed entity type with description and frequency estimate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityTypeProposal {
    /// Entity type name in UPPER_SNAKE_CASE (e.g. "PERSON", "LEGAL_CASE").
    pub name: String,
    /// Description of what this entity type represents.
    pub description: String,
    /// Estimated number of sampled documents containing this type.
    pub frequency: usize,
    /// Whether this is a baseline type (always included).
    pub is_baseline: bool,
}

/// A proposed relation type with description and entity type constraints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelationTypeProposal {
    /// Relation type name in lower_snake_case (e.g. "employs", "filed_in").
    pub name: String,
    /// Description of what this relation represents.
    pub description: String,
    /// Source entity type constraint.
    pub source_type: String,
    /// Target entity type constraint.
    pub target_type: String,
    /// Estimated number of sampled documents exhibiting this relation.
    pub frequency: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_schema_status_default() {
        assert_eq!(SchemaStatus::default(), SchemaStatus::None);
    }

    #[test]
    fn test_schema_status_serde() {
        let proposed = SchemaStatus::Proposed;
        let json = serde_json::to_string(&proposed).unwrap();
        assert_eq!(json, "\"proposed\"");

        let deserialized: SchemaStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, SchemaStatus::Proposed);
    }

    #[test]
    fn test_schema_proposal_serde_roundtrip() {
        let proposal = SchemaProposal {
            status: SchemaStatus::Proposed,
            entity_types: vec![EntityTypeProposal {
                name: "PERSON".to_string(),
                description: "A named individual".to_string(),
                frequency: 18,
                is_baseline: true,
            }],
            relation_types: vec![RelationTypeProposal {
                name: "employs".to_string(),
                description: "Employment relationship".to_string(),
                source_type: "ORGANIZATION".to_string(),
                target_type: "PERSON".to_string(),
                frequency: 5,
            }],
            sample_size: 20,
            total_documents: 200,
            domain_hint: Some("legal".to_string()),
            proposed_at: 1700000000000,
            reviewed_at: None,
            sampling_metadata: None,
        };

        let json = serde_json::to_string(&proposal).unwrap();
        let deserialized: SchemaProposal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.status, SchemaStatus::Proposed);
        assert_eq!(deserialized.entity_types.len(), 1);
        assert_eq!(deserialized.relation_types.len(), 1);
        assert_eq!(deserialized.sample_size, 20);
    }

    #[test]
    fn test_schema_proposal_backward_compat_no_sampling_metadata() {
        // Simulate old JSON without sampling_metadata field
        let json = r#"{
            "status": "proposed",
            "entity_types": [],
            "relation_types": [],
            "sample_size": 10,
            "total_documents": 100,
            "domain_hint": null,
            "proposed_at": 1700000000000,
            "reviewed_at": null
        }"#;
        let deserialized: SchemaProposal = serde_json::from_str(json).unwrap();
        assert!(deserialized.sampling_metadata.is_none());
    }

    #[test]
    fn test_suggest_schema_input_default() {
        let input = SuggestSchemaInput::default();
        assert!(input.domain_description.is_none());
        assert!(input.expected_entity_types.is_none());
        assert!(input.expected_relationship_types.is_none());
        assert!(input.domain_hint.is_none());
        assert!(input.sample_budget.is_none());
    }

    #[test]
    fn test_sampling_metadata_serde() {
        let meta = SamplingMetadata {
            total_documents: 100,
            sampled_count: 24,
            buckets: BucketBreakdown {
                short: BucketInfo { available: 30, sampled: 8 },
                medium: BucketInfo { available: 50, sampled: 8 },
                long: BucketInfo { available: 20, sampled: 8 },
            },
            topic_clusters_found: 5,
            auto_persona: None,
        };
        let json = serde_json::to_string(&meta).unwrap();
        let deserialized: SamplingMetadata = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.total_documents, 100);
        assert_eq!(deserialized.sampled_count, 24);
        assert_eq!(deserialized.buckets.short.available, 30);
    }
}
