//! Schema proposal types for LLM-based schema suggestion.
//!
//! These types represent the schema lifecycle: a proposal generated by
//! sampling documents and analyzing them with an LLM, which can then be
//! reviewed, approved, or rejected before ingestion begins.

use serde::{Deserialize, Serialize};

/// Status of a schema proposal in its lifecycle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SchemaStatus {
    /// No schema has been proposed yet.
    None,
    /// Schema has been proposed but not yet reviewed.
    Proposed,
    /// Schema has been approved for use in ingestion.
    Approved,
    /// Schema was rejected and needs revision.
    Rejected,
}

impl Default for SchemaStatus {
    fn default() -> Self {
        SchemaStatus::None
    }
}

/// A complete schema proposal generated by analyzing sampled documents.
///
/// Contains proposed entity and relation types along with metadata about
/// the sampling and review process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaProposal {
    /// Current status of the schema.
    pub status: SchemaStatus,
    /// Proposed entity types with descriptions and frequency counts.
    pub entity_types: Vec<EntityTypeProposal>,
    /// Proposed relation types with descriptions and constraints.
    pub relation_types: Vec<RelationTypeProposal>,
    /// Number of documents sampled.
    pub sample_size: usize,
    /// Total documents in dataset.
    pub total_documents: usize,
    /// Optional domain hint provided by partner.
    pub domain_hint: Option<String>,
    /// When the proposal was generated (epoch milliseconds).
    pub proposed_at: i64,
    /// When the proposal was approved/rejected (epoch milliseconds), if applicable.
    pub reviewed_at: Option<i64>,
}

/// A proposed entity type with description and frequency estimate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityTypeProposal {
    /// Entity type name in UPPER_SNAKE_CASE (e.g. "PERSON", "LEGAL_CASE").
    pub name: String,
    /// Description of what this entity type represents.
    pub description: String,
    /// Estimated number of sampled documents containing this type.
    pub frequency: usize,
    /// Whether this is a baseline type (always included).
    pub is_baseline: bool,
}

/// A proposed relation type with description and entity type constraints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelationTypeProposal {
    /// Relation type name in lower_snake_case (e.g. "employs", "filed_in").
    pub name: String,
    /// Description of what this relation represents.
    pub description: String,
    /// Source entity type constraint.
    pub source_type: String,
    /// Target entity type constraint.
    pub target_type: String,
    /// Estimated number of sampled documents exhibiting this relation.
    pub frequency: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_schema_status_default() {
        assert_eq!(SchemaStatus::default(), SchemaStatus::None);
    }

    #[test]
    fn test_schema_status_serde() {
        let proposed = SchemaStatus::Proposed;
        let json = serde_json::to_string(&proposed).unwrap();
        assert_eq!(json, "\"proposed\"");

        let deserialized: SchemaStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, SchemaStatus::Proposed);
    }

    #[test]
    fn test_schema_proposal_serde_roundtrip() {
        let proposal = SchemaProposal {
            status: SchemaStatus::Proposed,
            entity_types: vec![EntityTypeProposal {
                name: "PERSON".to_string(),
                description: "A named individual".to_string(),
                frequency: 18,
                is_baseline: true,
            }],
            relation_types: vec![RelationTypeProposal {
                name: "employs".to_string(),
                description: "Employment relationship".to_string(),
                source_type: "ORGANIZATION".to_string(),
                target_type: "PERSON".to_string(),
                frequency: 5,
            }],
            sample_size: 20,
            total_documents: 200,
            domain_hint: Some("legal".to_string()),
            proposed_at: 1700000000000,
            reviewed_at: None,
        };

        let json = serde_json::to_string(&proposal).unwrap();
        let deserialized: SchemaProposal = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.status, SchemaStatus::Proposed);
        assert_eq!(deserialized.entity_types.len(), 1);
        assert_eq!(deserialized.relation_types.len(), 1);
        assert_eq!(deserialized.sample_size, 20);
    }
}
